const COMMAND_BANK = "bank";
const COMMAND_SETTINGS = "settings";
const COMMAND_RETURN = "return";
const COMMAND_CURRENCY = "currency";
const COMMAND_COUNTRY_CODE = "country code";
const COMMAND_COUNTRY = "country";
const COMMAND_THRESHOLD = "threshold";

const ALL_COMMANDS = [
    COMMAND_BANK,
    COMMAND_SETTINGS,
    COMMAND_RETURN,
    COMMAND_CURRENCY,
    COMMAND_COUNTRY_CODE,
    COMMAND_COUNTRY,
    COMMAND_THRESHOLD
];

export {
    ALL_COMMANDS,
    COMMAND_BANK,
    COMMAND_COUNTRY,
    COMMAND_COUNTRY_CODE,
    COMMAND_CURRENCY,
    COMMAND_RETURN,
    COMMAND_SETTINGS,
    COMMAND_THRESHOLD
}